# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Log-Log4perl
version:      1.00
version_from: lib/Log/Log4perl.pm
installdirs:  site
requires:
    File::Spec:                    0.82
    Test::More:                    0.45

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
