--- #YAML:1.0
name:               Log-Log4perl
version:            1.23
abstract:           Log4j implementation for Perl
author:
    - Mike Schilli <m@perlmeister.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Spec:  0.82
    Test::More:  0.45
resources:
    MailingList:  mailto:log4perl-devel@lists.sourceforge.net
    repository:   http://github.com/mschilli/log4perl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
